project:
  type: book
  output-dir: content

book:
  title: "Change Management"
  subtitle: "F-cluster HAN Business Management Studies"
  author: "Witek ten Hove"
  date: "3/11/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

